# Makefile for Max OS X on github

COMPILER=gnu-gfortran
include $(COMPILATION_DIR)/Makefiles/Compilers/Makefile.$(COMPILER)

USE_LOCAL_SPFUNC=on

ifeq ($(USE_FFT),fftw3)
	FFT_LIB = -L/usr/local/Cellar/fftw/3.3.4_1/lib -lfftw3 -lfftw3f
	FFT_INC = -I/usr/include
endif

ifdef USE_NETCDF
	NETCDF_INC = -I/usr/local/lib
	NETCDF_LIB = -L/usr/local/lib/libnetcdff.dylib -L/opt/homebrew/include -lnetcdf
endif
