# Run these tests automatically on Github
# on every push and pull request.
name: NumericalTestsCookie
on: [push, pull_request]

# We run in a bash shell
defaults:
  run:
    shell: bash

# First build stella, and then perform python tests
jobs:

  # Build stella with Make  
  compile-stella:
    name: "Compile stella with make"  
    runs-on: ubuntu-latest
    env:
      OMPI_MCA_rmaps_base_oversubscribe: yes
      MPIRUN: mpiexec -np 
      
    steps:

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y gfortran make libfftw3-dev libnetcdf-dev libnetcdff-dev
          sudo apt install -y netcdf-bin python3 python3-pip openmpi-bin libopenmpi-dev
          export STELLA_SYSTEM=gnu_ubuntu

      # Print system information
      - name: System information
        run: |
          cat /etc/*release
          gfortran --version
          nf-config --all

      # Check-out repository under $GITHUB_WORKSPACE
      - name: Check out repository
        uses: actions/checkout@v4
          
      # Check $GITHUB_WORKSPACE
      - name: Check GITHUB_WORKSPACE
        run: | 
          echo " "; echo "Running directory:"; echo "  $(pwd)"
          echo " "; echo "Files in directory:"; echo "$(ls -la | sed 's/^/  /')"

      # Build stella executable
      - name: Build stella  
        run: |
          git submodule update --init --recursive
          make -j 12
          
      # Upload stella 
      - name: Upload stella 
        uses: actions/upload-artifact@v4
        with:
          name: stella-executable
          path: stella
          retention-days: 1

  # Run automatic python tests, after stella has been compiled
  numerical-tests: 
    needs: compile-stella
    runs-on: ubuntu-latest
    env:
      OMPI_MCA_rmaps_base_oversubscribe: yes
      MPIRUN: mpiexec -np 
    
    # Run the same set-up multiple times
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: "Numerical python tests 1"
          - name: "Numerical python tests 2"
          - name: "Numerical python tests 3"
          - name: "Numerical python tests 4"
          - name: "Numerical python tests 5"
      
    steps:

      # Install dependencies
      - name: Install dependencies
        run: | 
          sudo apt update
          sudo apt install -y gfortran make libfftw3-dev libnetcdf-dev libnetcdff-dev
          sudo apt install -y netcdf-bin python3 python3-pip openmpi-bin libopenmpi-dev
          export STELLA_SYSTEM=gnu_ubuntu

      # Install python environment
      - name: Install automated stella test dependencies
        run: pip3 install --user -r AUTOMATIC_TESTS/requirements.txt

      # Check-out repository under $GITHUB_WORKSPACE
      - name: Check out repository
        uses: actions/checkout@v4

      # Download stella executable from previous job
      - name: Download stella 
        uses: actions/download-artifact@v4
        with:
           name: stella-executable
          
      # Make stella executable
      - name: Make stella executable
        run: |
            echo " "; echo "Make stella executable:"; chmod +x stella
            echo " "; echo "Running directory:"; echo "  $(pwd)"
            echo " "; echo "Files in directory:"; echo "$(ls -la | sed 's/^/  /')"

      # Perform python tests 1
      - name: Perform numerical tests 1 for stella with Python
        if: ${{ contains(matrix.config.name, 'tests 1') }}
        run: | 
          export STELLA_SYSTEM=gnu_ubuntu
          make numerical-tests-1

      # Perform python tests 2
      - name: Perform numerical tests 2 for stella with Python
        if: ${{ contains(matrix.config.name, 'tests 2') }}
        run: | 
          export STELLA_SYSTEM=gnu_ubuntu
          make numerical-tests-2

      # Perform python tests 3
      - name: Perform numerical tests 3 for stella with Python
        if: ${{ contains(matrix.config.name, 'tests 3') }}
        run: | 
          export STELLA_SYSTEM=gnu_ubuntu
          make numerical-tests-3

      # Perform python tests 4
      - name: Perform numerical tests 1 for stella with Python
        if: ${{ contains(matrix.config.name, 'tests 4') }}
        run: | 
          export STELLA_SYSTEM=gnu_ubuntu
          make numerical-tests-4

      # Perform python tests 5
      - name: Perform numerical tests 5 for stella with Python
        if: ${{ contains(matrix.config.name, 'tests 5') }}
        run: | 
          export STELLA_SYSTEM=gnu_ubuntu
          make numerical-tests-1




