# Run these tests automatically on Github on every push and pull request.
# Use the macOS operating system, which has 4 cores.
name: Check stella on macOS
on: [push, pull_request]

# We always run in a bash shell
defaults:
  run:
    shell: bash

# First build stella, and then perform python tests
jobs:

#-----------------------------------------------------------------------
#                             Check stella                             
#-----------------------------------------------------------------------
  check-stella:
    
    # Run the same set-up multiple times
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12, macos-13]
        compiler: [Make, CMake]
    
    # Operating system
    runs-on: ${{ matrix.os }}
      
    # Steps
    steps:

      # Build stella, pass the operating system as an input
      - name: Build stella (step)
        uses: ./.github/workflows/build_stella.yml
        with:
          os: ${{ matrix.os }}
        secrets: inherit
          
      # Check $GITHUB_WORKSPACE
      - name: Check Github Workspace
        run: | 
          echo " "; echo "Running directory:"; echo "  $(pwd)"
          echo " "; echo "Files in directory:"; echo "$(ls -la | sed 's/^/  /')"


#-----------------------------------------------------------------------
#                             Python tests                              
#-----------------------------------------------------------------------

  # Run automatic python tests, after stella has been compiled
  numerical-tests: 
    needs: build-stella
    runs-on: macos-13
    env:
      OMPI_MCA_rmaps_base_oversubscribe: yes
      MPIRUN: mpiexec -np
      STELLA_SYSTEM: macos
    
    # Run the same set-up multiple times
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: "1 - Does stella run "
          - name: "2 - Geometry"
          - name: "3 - Gyrokinetic equation"
          - name: "4 - Flux tube"
          - name: "5 - Diagnostics"
      
    steps:

      # Install dependencies
      - name: Install dependencies
        run: brew install gcc@11 make openmpi fftw netcdf-fortran gnu-sed
      
      # Make the gfortran command available
      - name: Symlink gfortran (macOS)
        if: runner.os == 'macOS'
        run: | 
          sudo ln -s /usr/local/bin/gfortran-11 /usr/local/bin/gfortran
          sudo mkdir /usr/local/gfortran
          sudo ln -s /usr/local/Cellar/gcc@11/*/lib/gcc/11 /usr/local/gfortran/lib
          gfortran --version

      # Check-out repository under $GITHUB_WORKSPACE
      - name: Check out repository
        uses: actions/checkout@v4

      # Download stella executable from previous job
      - name: Download stella 
        uses: actions/download-artifact@v4
        with:
           name: stella-executable-macos-cmake
           
      # Make stella executable and run on 4 processors
      - name: Make stella executable
        run: |
            echo " "; echo "Make stella executable:"
            chmod +x stella
            echo " "; echo "Running directory:"; echo "  $(pwd)"
            echo " "; echo "Files in directory:"; echo "$(ls -la | sed 's/^/  /')"
            gsed -i 's/nproc = 16/nproc = 4/g' AUTOMATIC_TESTS/config.ini 
          
      # Install python environment
      - name: Install python virtual environment
        run: pip3 install --user -r AUTOMATIC_TESTS/requirements.txt

      # Perform python tests  
      - name: Numerical python tests
        run: |
          echo "matrix.config.name = ${{ matrix.config.name }}"
          echo "contains(matrix.config.name, '1 -') = ${{ contains(matrix.config.name, '1 -') }}"
          echo "contains(matrix.config.name, '2 -') = ${{ contains(matrix.config.name, '2 -') }}"
          echo "contains(matrix.config.name, '3 -') = ${{ contains(matrix.config.name, '3 -') }}"
          echo "contains(matrix.config.name, '4 -') = ${{ contains(matrix.config.name, '4 -') }}"
          echo "contains(matrix.config.name, '5 -') = ${{ contains(matrix.config.name, '5 -') }}"
          if ${{ contains(matrix.config.name, '1 -') }}; then 
             echo " FIRST LOOP "
             make numerical-tests-1
          elif ${{ contains(matrix.config.name, '2 -') }}; then 
             echo " SECOND LOOP "
             make numerical-tests-2
          elif ${{ contains(matrix.config.name, '3 -') }}; then 
             echo " THIRD LOOP "
             make numerical-tests-3
          elif ${{ contains(matrix.config.name, '4 -') }}; then 
             echo " FOURTH LOOP "
             make numerical-tests-4
          elif ${{ contains(matrix.config.name, '5 -') }}; then 
             echo " FIFTH LOOP "
             make numerical-tests-5
          fi 

# If the operating system is changed, we can check where modules are installed
# by reading the CMake cache file:
#    echo " "; echo "--------- DIRECTORIES ----------"
#    cat COMPILATION/build_cmake/CMakeCache.txt

# We can also install Homebrew and use the following lines of code
#    echo "Install Homebrew:"
#    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"; brew update
#    echo "FFTW_LIB_DIR=/opt/homebrew/lib/" >> $GITHUB_ENV; echo "Set FFTW_LIB_DIR"
#    echo "FFTW_INC_DIR=/opt/homebrew/include/" >> $GITHUB_ENV; echo "Set FFTW_INC_DIR"
#    echo "NETCDF_LIB_DIR=/opt/homebrew/lib/" >> $GITHUB_ENV; echo "Set NETCDF_LIB_DIR"
#    echo "NETCDF_INC_DIR=/opt/homebrew/include/" >> $GITHUB_ENV; echo "Set NETCDF_INC_DIR"
#    brew install gcc fftw netcdf netcdf-fortran open-mpi python
#    ln -sn /opt/homebrew/bin/gfortran-12 /opt/homebrew/bin/gfortran


