# Run these tests automatically on Github
# on every push and pull request.
name: NumericalTestsCookie
on: [push, pull_request]

# We run the in a bash shell
defaults:
  run:
    shell: bash

# Define the tests, for now we only have <standard_tests>
# where we define 3 seperate workflows in matrix/config/name
# For each of these workflows we need to perform the same
# initial steps: <Install dependencies>, <System information>
# Next, only the step corresponding to the test will be executed.
jobs:
        
  # Build stella with Make  
  compile-stella:
    name: "Compile stella with make"  
    runs-on: ubuntu-latest
    env:
      OMPI_MCA_rmaps_base_oversubscribe: yes
      MPIRUN: mpiexec -np 
      
    steps:
    
      # Install packages needed for stella compilation 	
      - name: Install dependencies
        run: sudo apt update &&
             sudo apt install -y
                 gfortran
                 make
                 libfftw3-dev
                 libnetcdf-dev
                 libnetcdff-dev
                 netcdf-bin
                 python3
                 python3-pip
                 openmpi-bin
                 libopenmpi-dev

	  # Check the system information		
      - name: System information
        run: |
          cat /etc/*release
          gfortran --version
          nf-config --all
      - uses: actions/checkout@v2 
        
      - name: Build stella in debug mode
        run: |
          set -ex
          export STELLA_SYSTEM=gnu_ubuntu_debug
          git submodule update --init --recursive
          make -I Makefiles -j12

  # Build stella with Make and run automatic fortran tests
  numerical-tests:
    name: "Perform fortran tests of the stella code" 
    runs-on: ubuntu-latest
    env:
      OMPI_MCA_rmaps_base_oversubscribe: yes
      MPIRUN: mpiexec -np 
      
    steps:
      - name: Install dependencies
        run: sudo apt update &&
             sudo apt install -y
                 gfortran
                 make
                 libfftw3-dev
                 libnetcdf-dev
                 libnetcdff-dev
                 netcdf-bin
                 python3
                 python3-pip
                 openmpi-bin
                 libopenmpi-dev

      - name: System information
        run: |
          cat /etc/*release
          gfortran --version
          nf-config --all
      - uses: actions/checkout@v2

      - name: Build stella 
        run: |
          set -ex
          export STELLA_SYSTEM=gnu_ubuntu
          git submodule update --init --recursive
          make -I Makefiles -j12

      - name: Build pFUnit library
        run: |
          set -ex
          export STELLA_SYSTEM=gnu_ubuntu
          make -I Makefiles -j4 build-pfunit-library  

      - name: Perform automated Fortran tests
        run: |
          set -ex
          export STELLA_SYSTEM=gnu_ubuntu 
          make -I Makefiles -j4 run-automated-fortran-tests 

